FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y curl git unzip xz-utils zip clang cmake ninja-build pkg-config \
    libgtk-3-dev liblzma-dev libstdc++-12-dev libglu1-mesa && \
    rm -rf /var/lib/apt/lists/*

ENV FLUTTER_ROOT=/home/user/flutter
ENV PUB_CACHE=/home/user/.pub-cache
ENV PATH=/home/user/flutter/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV CI=true
