FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y curl git unzip xz-utils zip clang cmake ninja-build pkg-config \
    libgtk-3-dev liblzma-dev libstdc++-12-dev libglu1-mesa

RUN mkdir -p /opt /workspace /root/.pub-cache

WORKDIR /workspace

ENV FLUTTER_ROOT=/opt/flutter
ENV PUB_CACHE=/root/.pub-cache
