/**
 * lib/github-storage.ts
 *
 * Centralized GitHub "Samaa Storage" helper.
 *
 * All generated Flutter projects are committed into a SINGLE repository
 * (GITHUB_STORAGE_REPO) organized by user and project:
 *
 *   samaa-storage/
 *     users/
 *       {clerkUserId}/
 *         {projectId}/
 *           app.ancl
 *           lib/main.dart
 *           pubspec.yaml
 *           README.md
 *
 * Required environment variables:
 *   GITHUB_TOKEN           — personal access token with repo scope
 *   GITHUB_STORAGE_OWNER   — GitHub username or org that owns the storage repo
 *   GITHUB_STORAGE_REPO    — name of the storage repository (default: "samaa-storage")
 */

import { getRepository, pushFilesToGitHub } from "@/lib/github-rest";

// ── Configuration ────────────────────────────────────────────────────────────

export function getStorageConfig(): {
  owner: string;
  repo: string;
  branch: string;
} {
  const owner = process.env.GITHUB_STORAGE_OWNER?.trim();
  const repo = (process.env.GITHUB_STORAGE_REPO?.trim()) || "samaa-storage";
  const branch = (process.env.GITHUB_STORAGE_BRANCH?.trim()) || "main";

  if (!owner) {
    throw new Error(
      "GITHUB_STORAGE_OWNER is not set. Add it to .env.local — this must be a GitHub username or org that owns the samaa-storage repo.",
    );
  }

  return { owner, repo, branch };
}

/**
 * The folder path inside the storage repo for a specific project.
 * Pattern: users/{clerkUserId}/{projectId}
 */
export function getStoragePath(clerkUserId: string, projectId: string): string {
  // Sanitize IDs to be safe for Git paths (Clerk IDs already use underscores)
  const safeUserId = clerkUserId.replace(/[^a-zA-Z0-9_-]/g, "_");
  const safeProjectId = projectId.replace(/[^a-zA-Z0-9_-]/g, "_");
  return `users/${safeUserId}/${safeProjectId}`;
}

/**
 * The GitHub web URL pointing to the project's folder in the storage repo.
 */
export function getStorageFolderUrl(
  owner: string,
  repo: string,
  branch: string,
  storagePath: string,
): string {
  return `https://github.com/${owner}/${repo}/tree/${branch}/${storagePath}`;
}

// ── Files builder ─────────────────────────────────────────────────────────────

function buildPubspec(projectName: string): string {
  const safeName = projectName
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, "_")
    .replace(/^[0-9]/, "app_$&");

  return [
    `name: ${safeName}`,
    `description: Flutter app generated by Samaa`,
    `publish_to: 'none'`,
    `version: 1.0.0+1`,
    ``,
    `environment:`,
    `  sdk: ">=3.2.0 <4.0.0"`,
    ``,
    `dependencies:`,
    `  flutter:`,
    `    sdk: flutter`,
    `  quickapp: any`,
    `  flutter_bloc: ^8.1.3`,
    `  equatable: ^2.0.5`,
    `  provider: ^6.1.2`,
    `  shared_preferences: ^2.3.2`,
    `  intl: ^0.19.0`,
    ``,
    `dev_dependencies:`,
    `  flutter_test:`,
    `    sdk: flutter`,
    `  flutter_lints: ^3.0.0`,
    ``,
    `flutter:`,
    `  uses-material-design: true`,
    ``,
  ].join("\n");
}

function buildReadme(
  projectName: string,
  description: string,
  storagePath: string,
): string {
  return [
    `# ${projectName}`,
    ``,
    `> ${description}`,
    ``,
    `Generated by **[Samaa](https://github.com/AffanShaikhsurab/samaa)** — an AI-powered Flutter app builder.`,
    ``,
    `**Storage path:** \`${storagePath}\``,
    ``,
    `## Getting Started`,
    ``,
    "```bash",
    `flutter pub get`,
    `flutter run`,
    "```",
    ``,
    `## Re-compile from ANCL`,
    ``,
    "```bash",
    `dart pub global activate quickapp`,
    `quickapp build app.ancl -o output/`,
    "```",
    ``,
    `## About`,
    ``,
    `The \`app.ancl\` file is the source of truth for this app.`,
    `ANCL (AI-Native Compressed Language) is compiled to full Flutter code by the \`quickapp\` package.`,
    ``,
  ].join("\n");
}

// ── Core publish function ─────────────────────────────────────────────────────

export type PublishToStorageParams = {
  clerkUserId: string;
  projectId: string;
  projectName: string;
  anclCode: string | undefined;
  flutterCode: string | undefined;
};

export type PublishToStorageResult = {
  commitSha: string;
  folderUrl: string;
  storagePath: string;
  fullRepoName: string;
  filesCount: number;
};

/**
 * Publish a generated Flutter project into the centralized samaa-storage repo.
 *
 * Instead of creating a new repo per project (old behavior), this commits files
 * into `users/{clerkUserId}/{projectId}/` within the shared storage repository.
 */
export async function publishToSamaaStorage(
  params: PublishToStorageParams,
): Promise<PublishToStorageResult> {
  const { clerkUserId, projectId, projectName, anclCode, flutterCode } = params;

  if (!anclCode && !flutterCode) {
    throw new Error("No ANCL or Flutter code available. Run ANCL generation first.");
  }

  if (!process.env.GITHUB_TOKEN?.trim()) {
    throw new Error("GITHUB_TOKEN is not configured. Cannot publish to GitHub.");
  }

  const { owner, repo, branch } = getStorageConfig();
  const storagePath = getStoragePath(clerkUserId, projectId);
  const safeProjectName =
    projectName?.replace(/[^a-zA-Z0-9\s]/g, "").trim() ?? "Samaa App";
  const description = `Flutter app: ${safeProjectName}`;

  // Get the default branch info (verifies repo exists + gets SHA)
  const repoInfo = await getRepository(owner, repo);
  const targetBranch = repoInfo.defaultBranch ?? branch;

  // Build file list with paths prefixed by the storage folder
  const files: Array<{ path: string; content: string }> = [];

  if (anclCode) {
    files.push({ path: `${storagePath}/app.ancl`, content: anclCode });
  }

  if (flutterCode) {
    files.push({ path: `${storagePath}/lib/main.dart`, content: flutterCode });
  }

  files.push({
    path: `${storagePath}/pubspec.yaml`,
    content: buildPubspec(safeProjectName),
  });

  files.push({
    path: `${storagePath}/README.md`,
    content: buildReadme(safeProjectName, description, storagePath),
  });

  const { commitSha } = await pushFilesToGitHub({
    owner,
    repo,
    branch: targetBranch,
    files,
    commitMessage: [
      `feat(${storagePath}): publish Flutter project`,
      ``,
      `App: ${safeProjectName}`,
      `ANCL source included: ${Boolean(anclCode)}`,
      `Pre-compiled Flutter code: ${Boolean(flutterCode)}`,
    ].join("\n"),
  });

  const fullRepoName = `${owner}/${repo}`;
  const folderUrl = getStorageFolderUrl(owner, repo, targetBranch, storagePath);

  return {
    commitSha,
    folderUrl,
    storagePath,
    fullRepoName,
    filesCount: files.length,
  };
}
